[package]
name = "bandwhich"
version = "0.22.2"
authors = [
  "Aram Drevekenin <aram@poor.dev>",
  "Eduardo Toledo <etoledom@icloud.com>",
  "Eduardo Broto <ebroto@tutanota.com>",
  "Kelvin Zhang <zhangxp1998@gmail.com>",
  "Brooks Rady <b.j.rady@gmail.com>",
  "cyqsimon <28627918+cyqsimon@users.noreply.github.com>",
]
categories = ["network-programming", "command-line-utilities"]
edition = "2021"
exclude = ["src/tests/*", "demo.gif"]
homepage = "https://github.com/imsnif/bandwhich"
keywords = ["networking", "utilization", "cli"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/imsnif/bandwhich"
rust-version = "1.74.0"
description = "Display current network utilization by process, connection and remote IP/hostname"

[dependencies]
anyhow = { version = "1.0.79", features = ["backtrace"] }
async-trait = "0.1.77"
chrono = "0.4"
clap-verbosity-flag = "2.2.0"
clap = { version = "4.5.1", features = ["derive"] }
crossterm = "0.27.0"
derivative = "2.2.0"
ipnetwork = "0.20.0"
itertools = "0.12.1"
log = "0.4.20"
once_cell = "1.19.0"
pnet = "0.34.0"
pnet_macros_support = "0.34.0"
ratatui = "0.25.0"
resolv-conf = "0.7.0"
simplelog = "0.12.1"
thiserror = "1.0.56"
tokio = { version = "1.35", features = ["rt", "sync"] }
trust-dns-resolver = "0.23.2"
unicode-width = "0.1.11"
strum = { version = "0.26.1", features = ["derive"] }

[target.'cfg(target_os = "linux")'.dependencies]
procfs = "0.16.0"

[target.'cfg(any(target_os = "macos", target_os = "freebsd"))'.dependencies]
regex = "1.10.3"

[target.'cfg(target_os = "windows")'.dependencies]
netstat2 = "0.9.1"
sysinfo = "0.30.5"

[dev-dependencies]
insta = "1.34.0"
packet-builder = { version = "0.7.0", git = "https://github.com/cyqsimon/packet_builder.git", branch = "patch-update" }
pnet_base = "0.34.0"
regex = "1.10.3"
rstest = "0.18.2"

[build-dependencies]
anyhow = "1.0.79"
clap = { version = "4.5.1", features = ["derive"] }
clap-verbosity-flag = "2.2.0"
clap_complete = "4.4.9"
clap_mangen = "0.2.18"
derivative = "2.2.0"
strum = { version = "0.26.1", features = ["derive"] }

[target.'cfg(target_os = "windows")'.build-dependencies]
http_req = "0.10.2"
zip = "0.6.6"
