[package]
edition = "2021"
name = "bandwhich"
description = "Display current network utilization by process, connection and remote IP/hostname"
version = "0.20.0"
rust-version = "1.70.0"
homepage = "https://github.com/imsnif/bandwhich"
repository = "https://github.com/imsnif/bandwhich"
readme = "README.md"
authors = [
  "Aram Drevekenin <aram@poor.dev>",
  "Eduardo Toledo <etoledom@icloud.com>",
  "Eduardo Broto <ebroto@tutanota.com>",
  "Kelvin Zhang <zhangxp1998@gmail.com>",
  "Brooks Rady <b.j.rady@gmail.com>",
  "cyqsimon <28627918+cyqsimon@users.noreply.github.com>",
]
keywords = ["networking", "utilization", "cli"]
categories = ["network-programming", "command-line-utilities"]
license = "MIT"
exclude = ["src/tests/*", "demo.gif"]

[dependencies]
pnet = "0.34.0"
ipnetwork = "0.20.0"
ratatui = "0.23.0"
crossterm = "0.27.0"
clap = { version = "4.4.4", features = ["derive"] }
chrono = "0.4"
regex = "1.9.5"
tokio = { version = "1.32", features = ["rt", "sync"] }
trust-dns-resolver = "0.23.0"
async-trait = "0.1.73"
unicode-width = "0.1.10"
resolv-conf = "0.7.0"
pnet_macros_support = "0.34.0"
anyhow = { version = "1.0.75", features = ["backtrace"] }
thiserror = "1.0.48"

[target.'cfg(target_os="windows")'.dependencies]
netstat2 = "0.9.1"
sysinfo = "0.29.10"

[target.'cfg(target_os="linux")'.dependencies]
procfs = "0.15.1"

[dev-dependencies]
insta = "1.31.0"
pnet_base = "0.34.0"
packet-builder = { version = "0.7.0", git = "https://github.com/cyqsimon/packet_builder.git", branch = "patch-update" }

[target.'cfg(target_os="windows")'.build-dependencies]
anyhow = "1.0.75"
http_req = "0.9.3"
zip = "0.6.6"
