[package]
edition = "2018"
name = "what"
description = "Display current network utilization by process, connection and remote IP/hostname"
version = "0.3.0"
homepage = "https://github.com/imsnif/what"
repository = "https://github.com/imsnif/what"
readme = "README.md"
authors = ["Aram Drevekenin <aram@poor.dev>"]
keywords = ["networking", "utilization", "cli"]
categories = ["network-programming", "command-line-utilities"]
license = "MIT"
exclude = ["src/tests/*", "demo.gif"]

[dependencies]
pnet = "0.22.0"
procfs = "0.5.3"
ipnetwork = "0.14.0"
tui = "0.5"
termion = "1.5"
structopt = "0.3"
dns-lookup = "1.0.1"
signal-hook = "0.1.10"
failure = "0.1.6"
chrono = "0.4"

[dev-dependencies]
insta = "0.11.0"
cargo-insta = "0.11.0"
packet-builder = "0.3.0"
pnet_base = "0.22.0"
regex = "1"
