[package]
name = "bandwhich"
version = "0.21.1"
authors = [
  "Aram Drevekenin <aram@poor.dev>",
  "Eduardo Toledo <etoledom@icloud.com>",
  "Eduardo Broto <ebroto@tutanota.com>",
  "Kelvin Zhang <zhangxp1998@gmail.com>",
  "Brooks Rady <b.j.rady@gmail.com>",
  "cyqsimon <28627918+cyqsimon@users.noreply.github.com>",
]
categories = ["network-programming", "command-line-utilities"]
edition = "2021"
exclude = ["src/tests/*", "demo.gif"]
homepage = "https://github.com/imsnif/bandwhich"
keywords = ["networking", "utilization", "cli"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/imsnif/bandwhich"
rust-version = "1.70.0"
description = "Display current network utilization by process, connection and remote IP/hostname"

[dependencies]
anyhow = { version = "1.0.75", features = ["backtrace"] }
async-trait = "0.1.74"
chrono = "0.4"
clap-verbosity-flag = "2.1.0"
clap = { version = "4.4.7", features = ["derive"] }
crossterm = "0.27.0"
derivative = "2.2.0"
ipnetwork = "0.20.0"
itertools = "0.11.0"
log = "0.4.20"
once_cell = "1.18.0"
pnet = "0.34.0"
pnet_macros_support = "0.34.0"
ratatui = "0.23.0"
resolv-conf = "0.7.0"
simplelog = "0.12.1"
thiserror = "1.0.50"
tokio = { version = "1.33", features = ["rt", "sync"] }
trust-dns-resolver = "0.23.1"
unicode-width = "0.1.11"

[target.'cfg(target_os = "linux")'.dependencies]
procfs = "0.15.1"

[target.'cfg(any(target_os = "macos", target_os = "freebsd"))'.dependencies]
regex = "1.10.1"

[target.'cfg(target_os = "windows")'.dependencies]
netstat2 = "0.9.1"
sysinfo = "0.29.10"

[dev-dependencies]
insta = "1.34.0"
packet-builder = { version = "0.7.0", git = "https://github.com/cyqsimon/packet_builder.git", branch = "patch-update" }
pnet_base = "0.34.0"
regex = "1.10.1"
rstest = "0.18.2"

[target.'cfg(target_os = "windows")'.build-dependencies]
anyhow = "1.0.75"
http_req = "0.10.1"
zip = "0.6.6"
